### ISSUE TITLE
Implement sensible behaviour for Enter

### ISSUE THREAD

**Issue by paulie-g** [SamHH/bukubrow#101]
When adding a bookmark, [Enter] should be equivalent to clicking on 'Add bookmark'. If I have something in the tag field at that time, [Enter] should be equivalent to 'Add tag' -> 'Add bookmark'.

**Comment by SamHH** [comment]
https://github.com/SamHH/bukubrow/commit/b8ddfccbfc854c4ab704314cc6c1b9f6e9b7eff2

Enter key anywhere except tag input will add the bookmark. Enter key within the tag input will add the tag.

**Comment by paulie-g** [comment]
It's a bit churlish to ask, but this commit doesn't quite go far enough.

Firstly, [Enter] does not add the bookmark unless the cursor is in an editbox currently. Removing the focus from it, or not placing it there in the first place defeats the enter-to-add. So the workflow where you open the add bookmark window and, being happy with what you see, hit enter doesn't work.

Secondly, enter does indeed now add tags if the cursor is in the tag editbox. However, after you've thusly added them, hitting enter doesn't add the bookmark. This breaks the workflow of adding tags and then adding the bookmark without the use of the mouse.

I realize this may not be the use case you're aiming for, but I've a bad shoulder and prefer to avoid using the mouse unless absolutely necessary. I can set a custom shortcut to open the extension window itself (chromium uses ctrl+shift+b for something else). I'd like to be able to open the add window with the keyboard as well, but haven't found a way to do that. Having opened the add bookmark window, however, I can now edit everything tabbing between fields, and with this commit add tags as well, but I can't finish the job and add the actual bookmark ;)

I've looked at the code (and this particular commit) and, once again, between typescript and whatever dark magic you're using on top, it's not at all clear to me how I might achieve any of those things. It's a bit embarrassing frankly ;)

**Comment by SamHH** [comment]
Thanks for the feedback, there is certainly room for improvement here. I've pushed up a few commits this afternoon. I'm trying to make it usable without straying too far from web norms and standards.

The first input in the bookmark form is now auto-focused. Additionally I've cleaned up the `tabIndex`es which control tabbing behaviour, and I've made the styling of the buttons take note of when they're focused. You should now be able to `Tab` and `Shift+Tab` your way around the form with ease, always submitting the form except when the tag input specifically is highlighted, in which case it adds the tag.

I'm also someone who tries to use the keyboard for everything so I've opened issue https://github.com/SamHH/bukubrow/issues/107. Anything keyboard navigation-related beyond the remit of the bookmark form should go in there, and will probably be addressed in a future release.

**Comment by SamHH** [comment]
Marking this as complete for now, any further improvements can go into #107.
