### ISSUE TITLE
Malformed URLs break binary deserialisation

### ISSUE THREAD

**Issue by paulie-g** [SamHH/bukubrow#102]
The functionality in #29 is biting me in mein Arsch. Namely, bukubrow has been reporting that I have 451 other bookmarks besides those rendered for ages now. Loading the remainder does not load all of them either. I'm at ~700 now.

I should add that adding bookmarks is still working. Presumably that means that the native messaging is working correctly, yes? Lmk if it's something I need to debug on my end.

**Comment by SamHH** [comment]
This is curious, nobody else has ever reported this. My best guess is that perhaps you've got some bookmarks formatted in a manner the binary/native messenger doesn't understand, those bookmarks fail deserialisation, and therefore they simply never make it over to the WebExtension. Let's see...

Can you see anything different about those that aren't appearing in Bukubrow versus those that are (in Buku)? Finding one that doesn't appear, if you recreate it in Bukubrow - assuming that works - does it look identical in Buku? What about in SQLite? *

\* Refer to [this](https://github.com/SamHH/bukubrow/issues/64#issuecomment-429649565) comment for accessing the Buku database. Basic SQL knowledge will help. :grin:

**Comment by paulie-g** [comment]
Since brow doesn't sort entries, how would I go about doing that? Is there
debug logging in the helper?

**Comment by SamHH** [comment]
Bukubrow does sort entries (supposed to anyway :eyes: does for me), first by URL match and second by title.

I'd advise comparing in Buku CLI.

**Comment by paulie-g** [comment]
I misread #92 then. What's the default sort, by id? If not, how would I reproduce that sort order in the cli?

**Comment by SamHH** [comment]
Yep, they're sorted on render (with memoisation for efficiency). That issue/commit was just to stop sorting upon receiving the bookmarks from the binary as, given the render sorting, it was pointless.

It's not the sort order I'm concerned about, it's the appearance of anything within the bookmarks themselves. Just filter to them in Buku (I can't remember how, but it's certainly possible) and see if there are any differences. Alternatively try retrieving the rows in SQLite.

**Comment by paulie-g** [comment]
They stop loading after initial_loaded_num + 491. If I want to look at that_number + 1 to see if it's failing somehow, I need to know the sort order.

**Comment by paulie-g** [comment]
Ok, tracked it down. There was a bookmark that had an invalid url, inserted by way of my custom script (it inserts whatever xsel gives it). Buku itself handles that fine. In fact, I was planning to use that more as a way to insert arbitrary notes.

My view is that bukubrow shouldn't break if it encounters such a thing. It may not make sense to load it or display it, but it ought not break. I understand if you disagree though. Good pointer on malformed bookmark causing a serde problem, saved me lots of time.

**Comment by paulie-g** [comment]
Tried finding where this happens so I can fix it, but no luck - I just don't understand enough about how TypeScript does types. Even if I could find where url is defined, I've no idea how to ignore a single error and continue. Hopefully it's possible to resume a generator that's thrown an exception.

Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at backend.build.js:1
    at Object.map (backend.build.js:1)
    at backend.build.js:1
    at Generator.next (<anonymous>)
    at i (backend.build.js:1)
backend.build.js:1 Uncaught (in promise) Error: Failed to fetch bookmarks
    at Object.Nothing (backend.build.js:1)
    at Object.caseOf (backend.build.js:1)
    at backend.build.js:1

**Comment by SamHH** [comment]
Thanks for the detective work :smile: 

Could you provide an example of a malformed URL that was breaking?

**Comment by paulie-g** [comment]
Steps to reproduce: Add a bookmark with url='foo', tags='test1,test2'.

**Comment by SamHH** [comment]
Perfect repro, thank you. (Note to self: `buku -a 'bad-url'`)

I think master branch is handling error cases better already as it's just giving me an error rather than exhibiting any of that other peculiar behaviour. Here's the bad response coming from the binary:

```called `Result::unwrap()` on an `Err` value: InvalidColumnType(2, Null)```

Looks like a binary bug!

**Comment by SamHH** [comment]
I think this has been fixed on master (https://github.com/SamHH/bukubrow/commit/ef5424b102a8f3be9b27bebcad5318d097a49c2d).

The binary was crashing upon attempting to deserialise a row with a null value; though Buku's SQLite schema does technically allow for null values in all but the id field, it's not something that I've seen Buku actually utilise except in this case whereby you've supplied a malformed URL, hence it not having been accounted for previously.

This binary change should be backwards-compatible, so you can either build it yourself or grab a prebuilt one from CI [here](https://dev.azure.com/samhhweb/Bukubrow/_build/results?buildId=49) - it'd be great to get this tested before I bump the versions. Speaking of which, I've only just transitioned across to using Azure for build artifacts so let me know how that goes if you go that route. I can attach files here directly if you have any trouble.

**Comment by paulie-g** [comment]
I looked at the row in sqlite and din't see it being NULL. Yes, the url is not a well-formed url, but sqlite isn't enforcing that requirement. I couldn't see anywhere that enforced it in the rust code either, so it looked to me like it was erroring out in the extension somewhere. Desc and tags can't be NULL because they've got default values in the schema. Consequently, the way you describe the bug happening doesn't make sense to me. I'm not sure if it's a deficit of understanding on my part, a shortcoming of the explanation or.. Normally there'd be a commit I could look at by way of explication.

All that said, I've rebuilt locally from the head of master and all is well. Not only does brow not refuse to load bookmarks past the malformed one, it actually loads and shows the malformed one as well.

**Comment by SamHH** [comment]
It doesn't seem to display null in SQLite if you do a SELECT statement, but I was able to positively test this by manually updating rows in there between null and an empty string. I'm going to assume that everything nullable (not non-nullable) can be null as this project is blindly beholden to the behaviour of Buku.

With regards to Rust, I think the SQLite library we're using was implicitly panicking when deserialisation failed, and it failed with null values as they didn't match the Bookmark struct. Note in that above commit I updated said library, which in turn allowed me to simply fix/workaround this issue by instructing each field to fallback to a default value matching the expected type when the result was Err.

Anyway, awesome that it's fixed! :confetti_ball:

**Comment by paulie-g** [comment]
`sqlite> .schema bookmarks`
`CREATE TABLE bookmarks (id integer PRIMARY KEY, URL text NOT NULL UNIQUE, metadata text default '', tags text default ',', desc text default '', flags integer default 0);`

Buku expects that this means those default values are used instead of the corresponding NULL values in an INSERT statement. It's wrong. If it wants the default values used, it needs to omit them from the insert or specify DEFAULT (if sqlite supports such a thing).
