### ISSUE TITLE
Bookmarked status not visible

### ISSUE THREAD

**Issue by paulie-g** [SamHH/bukubrow#104]
Currently, the page I'm on doesn't show as bookmarked unless it's loaded in the extension (so the first 20 or whatever the limit is). With #102 , it doesn't even show for the latest bookmarks if I instruct bukubrow to load the remainder.

I would suggest that you add a simple status query to your rust helper so the extension can ask if the current url is bookmarked without loading all of the bookmarks.

**Comment by SamHH** [comment]
Not going to address this one until #102 is resolved.

**Comment by paulie-g** [comment]
.. and you were right. Now that the issue in #102 is resolved, the problem does not occur.
