### ISSUE TITLE
CI / cross-compiling binary

### ISSUE THREAD

**Issue by SamHH** [SamHH/bukubrow#12]

**Comment by SamHH** [comment]
Added macOS release. Need to figure out cross-compiling in order to add Linux releases.

**Comment by HaoZeke** [comment]
Maybe a CI like cricle CI or wercker for docker based cross compiling would help? I could add a wercker.yml for *nix builds...

**Comment by SamHH** [comment]
Travis have just been bought by a shady company.

CircleCI don't support macOS without subscription.

Hmm...

**Comment by SamHH** [comment]
https://github.com/japaric/rust-cross/issues/22

**Comment by SamHH** [comment]
https://www.reddit.com/r/rust/comments/6rxoty/tutorial_cross_compiling_from_linux_for_osx/

**Comment by SamHH** [comment]
Done! Though for now I'll be manually adding the binaries to releases as needed. https://github.com/SamHH/bukubrow/pull/83
