### ISSUE TITLE
cp: cannot stat '~/chrome-host.json': No such file or directory

### ISSUE THREAD

**Issue by SamHH** [SamHH/bukubrow#16]
https://github.com/SamHH/bukubrow/issues/5#issuecomment-282785893

**Comment by SamHH** [comment]
@jarun

I think it failed because I didn't have the releases packaged the way they should be ready for the end-yser.

If you're on macOS, try this binary: https://github.com/SamHH/bukubrow/releases

If you're on Linux, I need to figure out cross-compiling before I can make releases for you. However, you can clone the repo, run `make binary-linux-x64` and then inside `./release` you'll have a zip identical to what you would have downloaded.

Then just follow install steps :-)

Let me know how it goes!

**Comment by jarun** [comment]
@SamHH Thanks! I'll check it out!

**Comment by jarun** [comment]
I tried on a VM with go installed. And it seems to install correctly. Please update the instructions in the readme as well.
