### ISSUE TITLE
handle go dependancy

### ISSUE THREAD

**Issue by teto** [SamHH/bukubrow#27]
make binary-linux-x64 would fail because it was missing a go package.
I am not familiar with the go environment but `go get github.com/mattn/go-sqlite3 ` solved it.

I would suggest to change the README to have step 1: download or generate binary (make binary-linux-x64).
2/ install binary.

Now I would like to add the addon to firefox but not sure which file it is ?

**Comment by SamHH** [comment]
> make binary-linux-x64 would fail because it was missing a go package.
I am not familiar with the go environment but go get github.com/mattn/go-sqlite3 solved it.

Are you a Linux or macOS user? I suspect that you're on Linux and this was just what it took to enable compilation at all. Something I will add to the README though, so thanks for the catch 👍 

> Now I would like to add the addon to firefox but not sure which file it is ?

Until I resubmit it to AMO and then eventually have it approved, you'll need to install it yourself locally. I've just fixed up the makefile a bit so you can install it like so:

1. Clone the repo.
2. Run `make webext-release`.
3. Unzip the zip found at `./release/webext.zip`.
4. Open the following URL in Firefox: `about:debugging#addons`. Click "Load Temporary Add-on" and navigate to the unzipped directory, and select `manifest.json`.

You'll need to do this each time you restart. Note that you'll also need to have registered the binary per the instructions in the README.

Doing this just now has shown me two things:

1. I really need to get the extension onto AMO, and until it's accepted I need to create a signed version that can be downloaded here.

2. The styling is a bit fucked.

3. The README could do with updating.

I'll look into each of these this week. 🔜

**Comment by teto** [comment]
I am on ubuntu 64 bits with firefox 53.0. I followed your instructions and the plugin is loaded in firefox.
Nevertheless, when I click bukubrow refresh icon, I get `An unknown error occurred.`. Any logfile or way to get a trace ?

**Comment by SamHH** [comment]
Click on the debug button beside Bukubrow in that temporary addons/debugging page and watch the console. When you click the fetch button you should with any luck get an error message logged starting with `...error fetching bookmarks:`.

**Comment by teto** [comment]
With the version installed from firefox repository, in debug mode, there are many messages but I believe these are the relevant ones for bukubrow ?
```
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:265
	withLastError resource://gre/modules/ExtensionCommon.jsm:265:9
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:316:11
Une tentative visant à définir un en-tête interdit à été bloquée : Connection  rs=AHGWq9Cb_fG5eb7RlU9cM0pp5yLZcPhBBQ:151:96
ReferenceError: yieldbot is not defined  Simple-knock-down-cardboard-end-table-flatpack:41:28
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. ExtensionCommon.jsm:265
Frontend loaded.  frontend.js:1:1
TypeError: state.bookmarks is undefined[En savoir plus]  frontend.js:13:36
ReferenceError: yieldbot is not defined
```

**Comment by SamHH** [comment]
Hey, are you still receiving this error? Please try with the latest version of the addon from the Firefox store and the latest binary here in the releases tab.

**Comment by teto** [comment]
From source, I have 2 errors:

```
$ make webext
make prepare
make[1] : on entre dans le répertoire « /home/teto/bukubrow »
mkdir -p .build release
make[1] : on quitte le répertoire « /home/teto/bukubrow »
cd webextension && npm run build

> bukubrow@1.1.1 build /home/teto/bukubrow/webextension
> rm -r ./dist/ && NODE_ENV=production webpack

rm: impossible de supprimer './dist/': Aucun fichier ou dossier de ce type

npm ERR! Linux 4.10.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! bukubrow@1.1.1 build: `rm -r ./dist/ && NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bukubrow@1.1.1 build script 'rm -r ./dist/ && NODE_ENV=production webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bukubrow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -r ./dist/ && NODE_ENV=production webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bukubrow
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bukubrow
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/teto/bukubrow/webextension/npm-debug.log
makefile:29 : la recette pour la cible « webext » a échouée

```
and when I try to run 
```
./binary/install.sh 

Select your browser:
====================
1) Chrome
2) Chromium
3) Firefox
1-3: 3

Installing Firefox host config
cp: impossible d'évaluer '/home/teto/bukubrow/binary/firefox-host.json': Aucun fichier ou dossier de ce type <--- translates to "file does not exist"
```

I've installed the firefox extension from official channels so don't need to install from source but I have to for the server component.

**Comment by SamHH** [comment]
Yeah, not to worry about the extension source for the reason you stated.

The binary though... make sure you're downloading it from the releases tab (`binary-darwin-x64.zip`) and not trying to build from (repo) source. I don't think the repo folder structure would work by default.

**Comment by SamHH** [comment]
The binary has been rewritten. If you're still experiencing issues @teto please make a new ticket. :-)
