### ISSUE TITLE
Keep synchronised / replacing browser's native bookmarks

### ISSUE THREAD

**Issue by SamHH** [SamHH/bukubrow#3]
## Initial thoughts

> One-way or two-way?

One-way. Buku should be considered the source of truth and two-way could potentially raise new issues/complexities.

> Does Buku have events for on change?

Even if it does, I'm not sure how we could access it. But worth looking at.

> If not, do we proceed with polling every nth seconds?

Probably, yes. Don't want to make it too often, but equally it will be a PITA if things are out of sync for more than a moment. Every 20 seconds? Need to profile the performance impact of checking the database and diffing that often. Or, potentially cheaper (again, needs profiling) would be simply swapping the bookmarks out instead of diffing. Undoubtedly easier too.

The alternative would be a button that you can hit to manually synchronise. In-fact, we could raise the interval between checks and have this as well as a compromise.

> What about edits to the browser's bookmarks?

We should be telling users to always edit bookmarks in Buku, I think.

**Comment by SamHH** [comment]
The alternative would be a simple key-activated dropdown, autofocusing an input, and a button for manual sync.

**Comment by SamHH** [comment]
^^ The above comment is where we're at now. Further experimentation / consideration is required regards replacing all the browser bookmarks with those found in Buku.

**Comment by CaptainQuirk** [comment]
Wouldn't it be possible for the extension to actually receive a push via websocket ? Could the go library act as a server through which every bookmark insertion/update/deletion could go ?

It would allow any client to update automatically.

**Comment by SamHH** [comment]
The extension is basically always listening, so it'd be possible to do this for sure in tandem with the relevant event on the WebExtension side (just checked, definitely exists). The question for this ticket is really more theoretical for want of a better word and less technical; how can it radically interface with both the browser bookmarks and Buku APIs without potentially causing problems for the user? What do users actually want?

Let's start with you @CaptainQuirk!

**Comment by CaptainQuirk** [comment]
Well, as someone mentioned in another thread, I also came to buku looking for an alternative to the late **delicio.us** service.

Spending most of my time in a terminal emulator, I'm perfectly ok with browsing existing bookmarks from there. Existing command line client don't really fit my needs but that's another issue !

However, I would expect for Bukubrow to spare me the pain to add a bookmark by copying and pasting from the browser to a terminal, which is not user friendly at all.

When browsing on a page, you have almost everything : a **url**, a **title** that doesn't need to be fetched with a request. You could even get tags from the <meta keywords> tag.
It also hit me that Buku allows you to store notes alongside the url. Wouldn't it be great to be able to read your notes on a side panel and sync them back ?
The browser is the best context to create a bookmark.
As for native bookmarking systems, I don't use them :laughing:

**Comment by CaptainQuirk** [comment]
> You could even get tags from the tag.

I meant : from the *<meta description>* tag

**Comment by SamHH** [comment]
Aha okay, seems like the right direction (from previous feedback also) would be to leave the native bookmarks alone and just add in a good UI for adding/editing bookmarks from the extension. Closing this in favour of #38 .
