### ISSUE TITLE
Input filtering

### ISSUE THREAD

**Issue by pejesat** [SamHH/bukubrow#34]
Hi thank you very much for your nice extension.
I've some wishs:
- always jump directly in the search field
- special char : could show results of buku -t (tags)
- special char :$name could search only in tag 
- special char + add bookmark
- special char - del bookmark
- special char w edit bookmark

thank you cu peje

**Comment by SamHH** [comment]
Autofocusing the search field is already working in Chrome/Blink/WebKit and I just finished released a workaround/hacky fix to make it work in Firefox/Gecko. I'm having some trouble updating the addon in the Firefox Addon Store so I'm not sure how soon you'll see it. If at present it's not working in Chrome/other browser then do let me know.

I like the idea of searching specific fields using special characters, for example `#tag`, `$name`, `>desc`, `:url`. My concern with this would be that if you're already in the search field - as you will almost always be - what's to say that you're searching for a `#tag` and not something with `#tag` in the name/url/etc? Perhaps that could be denoted by a space between them?

Editing the bookmarks is definitely something I'd like to add at some point. My concern regards shortcuts would echo the above; how do we know you want to `w` (edit) a bookmark and not search for something with the character `w` in it? Only solution I can think of at the moment would be Vim-like keyboard navigation, but that sounds... complicated and unlikely to work too well.

Let me know what you think. Thanks for the feedback 👍

**Comment by pejesat** [comment]
Hi Sam,nice to see that you are interessed.
First sorry for my bad english....

I think the best way would be an small grahpical toolbar on top of the 
search field.
-> it would possible to switch the mode by mouseclick or with shortcuts.
-> it would possible to indicate the actual modus per highlight.

As idea see the picture
best regards Peje

Am 2017-06-01 11:05, schrieb Sam A. Horvath-Hunt:

**Comment by SamHH** [comment]
Do you have a picture I could see to visualise what you mean? It can be as crudely drawn as you'd like haha. Cheers.

**Comment by pejesat** [comment]
As an Idea see this pic:
[http://imageshack.com/a/img922/1571/HQHPZH.png](url)
cu peje

**Comment by SamHH** [comment]
Interested in doing this at some point. Basic plan:

- Add a small menu at the top a la that image to change the filter (enable/disable each).

- Press e.g. `#` and then `tab` to signify that you want to enable the tag filter from the keyboard (tab will just check the last character before cursor, if possible). For chars see my earlier comment, I think that was logical.

- For adding/editing etc... hmm. Would need to flesh those sorts of features out themselves first. First step would be #38.

**Comment by SamHH** [comment]
Notes for self:

- Replace `<input>` with a [contentEditable](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content) piece of markup.
- Listen for tab input, and test for previous special char (e.g. #). Perhaps add a way to escape them e.g. by placing them in a "string"? Then give them special HTML... how to represent this in React state? Which in turn would be used by filter algo?
- Handle backspace over denoted search terms.

**Comment by SamHH** [comment]
An initial implementation of this feature has been merged into master and will (eventually) be released in `2.5.0`.

At present there are the following filters/rules:
- Searching for the name has to happen at the start of the input, and cannot begin with any of the special characters.
- Special characters:
  - `#` for tags.
  - `>` for description.
  - `:` for URL.
- You can use multiple of these in the filter in any order. The input differentiates between filters by looking for `<space><special char><text>`.
- The filter is strict in the sense that _all_ of your filters must match a given bookmark, though they can overlap. This can lead to some strange behaviour with the highlighting though I think you'd need to go looking for it to find that little bug. (There's a comment detailing it in the code if anyone is curious.)

What does this all mean? You can now do any of the following:

- `search only for bookmark name`
- `search for bookmark name and #this one tag`
- `search for bookmark name and #this tag and >this text in description and #this tag as well as >this text in description too`

Once you grep the very basic regex underpinning it it's fairly usable I think. Technical improvements are always welcome to any onlookers... this is my first rodeo with more complex regular expressions.

As for the input itself, you won't see any visual feedback yet - you'll have to understand if it's behaving correctly based upon the highlights in the filtered bookmarks. This is a surprisingly difficult problem to solve, and I wasn't really satisfied with any of the options I explored. I've created a ticket to track improvement on this front: #74

:confetti_ball:

**Comment by SamHH** [comment]
Also @pejesat some hotkeys were recently added, see #57. :-)
