### ISSUE TITLE
Update Firefox addon in store

### ISSUE THREAD

**Issue by SamHH** [SamHH/bukubrow#35]
I appear to have broken their store 🥇 haha

Tracking here: https://github.com/mozilla/addons-server/issues/5544

**Comment by SamHH** [comment]
Submit for approval 👍

**Comment by jarun** [comment]
@SamHH I came across this recently: https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/

I believe we don't have an issue with the Firefox 57 and beyond roadmap as bukubrow is a webextension already. Just wanted to double check with you...

**Comment by SamHH** [comment]
@jarun Yep, it's a WebExtension already. :-)

**Comment by jarun** [comment]
Thanks for confirming!
