### ISSUE TITLE
Ability to add new bookmarks

### ISSUE THREAD

**Issue by StefanLeupold** [SamHH/bukubrow#38]
I think the option to add the currently opened URL as a new bookmark to the buku database would be extremely valuable. Then the user would not have to use the command line except for deleting or editing entries.
I would very much appreciate that feature.

**Comment by nick-s-b** [comment]
I'd really like this feature as well. When delicious was still alive, I used to use a webextension to add URLs. Now that Delicious's dead, I'm using buku. But adding URLs is a pain.

Would it be possible to add something simple like this to bukubrow?

![https://i.imgur.com/ywcRPD0.png](https://i.imgur.com/ywcRPD0.png)

Thanks!

**Comment by SamHH** [comment]
This is possible and something I would like the implement. Notes to self re: db: https://github.com/jarun/Buku/issues/122#issuecomment-281352673

**Comment by CaptainQuirk** [comment]
Any news on this ?

**Comment by SamHH** [comment]
Just a question of when I have the time to do it, or someone else has the time to contribute a PR.

I did start doing some work locally unrelated to this ticket yesterday, but for some reason I can't get Chromium to communicate with the binary. Once I have that working I'll probably move onto this. (Though, again, a PR is also welcome!)

**Comment by CaptainQuirk** [comment]
Maybe we could make a list of things to do in both the binary and the webextension to get it working ?

## webextension

- [ ] mockup the add popup with following fields
  - title: prefilled with page title
  - keywords. Prefilled with meta keywords. Would be great if we had a nice list component like delicious used to
  - comment
  - save and cancel buttons
- [ ] think about config values
  - keyboard shortcut : string
  - fetch keywords : boolean
- [ ] retrieve page's `<title>`
- [ ] retrieve page's `<meta keywords>`
- [ ] display form on shortcut
- [ ] validate user input
- [ ] contact binary to save. Handle success or error

- [ ] handle bookmark edition

**Comment by SamHH** [comment]
The bulk of that time will be spent communicating with the binary, and ensuring that the binary is handling things in _exactly_ the same way as Buku does.

**Comment by SamHH** [comment]
Adding, editing, and deleting bookmarks has landed in 2.3.0! :confetti_ball: :confetti_ball: :confetti_ball: 

I would exercise caution with regards to this new release; ideally back up your Buku database and report back any issues. That said, I'm seeing no issues on my own personal Buku database.

**Comment by CaptainQuirk** [comment]
Hi,

I've installed the latest version to check it out ! Thanks for your work, I'm excited to use it !
