### ISSUE TITLE
Building the binary failed

### ISSUE THREAD

**Issue by debianuser3** [SamHH/bukubrow#40]
debianuser3@debian:/opt/bukubrow/bukubrow-1.1.1$ sudo make release
make webext
make[1]: Entering directory '/opt/bukubrow/bukubrow-1.1.1'
make prepare
make[2]: Entering directory '/opt/bukubrow/bukubrow-1.1.1'
mkdir -p .build release
make[2]: Leaving directory '/opt/bukubrow/bukubrow-1.1.1'
cd webextension && npm run build

> bukubrow@1.1.1 build /opt/bukubrow/bukubrow-1.1.1/webextension
> rm -r ./dist/ && NODE_ENV=production webpack

rm: cannot remove ‘./dist/’: No such file or directory

npm ERR! bukubrow@1.1.1 build: `rm -r ./dist/ && NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bukubrow@1.1.1 build script.
npm ERR! This is most likely a problem with the bukubrow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -r ./dist/ && NODE_ENV=production webpack
npm ERR! You can get their info via:
npm ERR!     npm owner ls bukubrow
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! cwd /opt/bukubrow/bukubrow-1.1.1/webextension
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/bukubrow/bukubrow-1.1.1/webextension/npm-debug.log
npm ERR! not ok code 0
makefile:29: recipe for target 'webext' failed
make[1]: *** [webext] Error 1
make[1]: Leaving directory '/opt/bukubrow/bukubrow-1.1.1'
makefile:63: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by SamHH** [comment]
I'll look into formally fixing this at a later date, but for the time being an easy fix should be editing `webextension/package.json` and changing each `rm -r` (lines 7 and 8) to `rm -rf`.

**Comment by debianuser3** [comment]
Thank you very much!
