### ISSUE TITLE
clarification about install.sh

### ISSUE THREAD

**Issue by KarlFiabeschi** [SamHH/bukubrow#41]
Hello
i am trying to create an aur package for firefox and i would like a clarification about how to installing process.

The .sh installer does nothing but copy the firefox.json in /Library/Application Support/Mozilla/NativeMessagingHosts and nothing else?

Is bukbrow.go excluded? what is it for?

thanks

**Comment by SamHH** [comment]
It also sets the path of the binary (see `%%replace%%`) inside host JSON to the CWD prior to moving the JSON file as you noted.

If you're foregoing `install.sh` then you'll need that path to correlate to where the binary will be located.

**Comment by KarlFiabeschi** [comment]
Hi,
thanks for your reply.
So if for example i put the bukubrow.go on /opt/ and edit the com.samhh.bukubr.json like this:

{
	"name": "com.samhh.bukubrow",
	"description": "Bukubrow binary for the Firefox extension",
	"path": "/opt/bukubrow.go",
	"type": "stdio",
	"allowed_extensions": [
		 "bukubrow@samhh.com"
	 ]
}

works?

**Comment by SamHH** [comment]
Nearly. Instead of placing and referencing the source Go file, you actually need to place and reference the compiled binary. You can find a precompiled macOS binary in the releases page. For Linux you'll need to follow the instructions in the README.

**Comment by KarlFiabeschi** [comment]
Ok thanks, now i understand. 

Sorry but i don't have familiarity with go binary & language.

I'll try to put an aur package together, if you are interested to it i can post here when is done.
