### ISSUE TITLE
compile fails on ubuntu 16

### ISSUE THREAD

**Issue by yodog** [SamHH/bukubrow#48]
apparently due to this error: https://github.com/rust-lang-nursery/bitflags/issues/138

is there any way to make it work on the latest version available on the repository?

```
$ apt-cache policy rustc
rustc:
  Installed: 1.17.0+dfsg2-8~ubuntu0.16.04.2
  Candidate: 1.17.0+dfsg2-8~ubuntu0.16.04.2

```

**Comment by SamHH** [comment]
Have you considered Rustup? https://www.rustup.rs

I don't have much time at the moment and am honestly not going to prioritise backwards compatibility for the binary.

Alternatively I've just attached a prebuilt binary for Linux here, let me know if it works for you: https://github.com/SamHH/bukubrow/releases/tag/2.0.0

**Comment by yodog** [comment]
yes, your compiled binary worked.
since you cant rework the code, maybe you could add a linux binary for every update? :+1: 
anyway, thank you for your time :)

**Comment by SamHH** [comment]
Will do, the reason I was able to this time unlike previously is that I just started dual booting Arch on my Macbook :-)

Glad to hear it's working!
