### ISSUE TITLE
Add to Chrome web store/Firefox addon store

### ISSUE THREAD

**Issue by SamHH** [SamHH/bukubrow#5]

**Comment by SamHH** [comment]
Blocked by #6.

**Comment by SamHH** [comment]
Submit to both!

Chrome is up: https://chrome.google.com/webstore/detail/bukubrow/ghniladkapjacfajiooekgkfopkjblpn

**Comment by SamHH** [comment]
Firefox is awaiting review.

**Comment by jarun** [comment]
I tried downloading the script and run it. Got this:

```
$ ./install.sh 

Select your browser:
====================
1) Chrome
2) Chromium
3) Firefox
1-3: 1

Installing Chrome host config
cp: cannot stat '/home/vaio/chrome-host.json': No such file or directory
```

Also, is there a way to just install the extension and use it without the manual steps?

**Comment by SamHH** [comment]
Hmm, I need to have another look at the install script. (#16)

No way to make it work without the install step to my knowledge unfortunately as we need native messaging to communicate with the host file system.
