### ISSUE TITLE
Old man on Chromebook (Toshiba 2)

### ISSUE THREAD

**Issue by kcstarr** [SamHH/bukubrow#52]
I finally got the basics down to Windows; now that I'm relegated to a Chromebook (I hate the NSA...oops...I mean Alphabet/Google lobbying/gook exec. mgtmt), but I love its OS ease of use. Therein, lies the problem. I commend u 4 this extension being Open-sourced, but most of the instructions on GitHub, may as well b in Cyrillic. I will willingly delete ur project but it sounds so very kewl. Are there any workarounds that wudn't require me to get another graduate degree? I've had bulldogs w/ better memory functions than I now possess. Cordially, & w/ mild embarrassment,  John Cannon

**Comment by SamHH** [comment]
First and foremost, you do presumably have Buku installed?
