### ISSUE TITLE
Insert Page information in the add a bookmark popup

### ISSUE THREAD

**Issue by CaptainQuirk** [SamHH/bukubrow#56]
Hi,

It would be great if you could grab the page title and the meta keywords to insert them in the add popup fields ! Would save a bit of time !

Thanks

**Comment by SamHH** [comment]
I'm not going to add meta keywords as from experience they can sometimes be ridiculously long, but I will add the page title by default like we do with the URL now. Would the description also be helpful?

**Comment by SamHH** [comment]
https://github.com/SamHH/bukubrow/commit/6064e9aef2aa5b822d240aee1d5adf4ae34c8280
