### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by CaptainQuirk** [SamHH/bukubrow#57]
Hi,

I would really much like to get the « add a bookmark » popup to be displayed on a shortcut ! Would it be possible ?

Thanks !

**Comment by SamHH** [comment]
These are now done in #70, though you'll need to wait for that PR to be merged and an update released before you can use it. For now, these are the hotkeys I've defined:

- Ctrl+D: Open add bookmark modal
- Ctrl+O: Open all bookmarks that match the current filter
- Ctrl+R: Refresh bookmarks
- Ctrl+L: Focus search input

You may want to track #7 for the ability to edit these bindings.

**Comment by CaptainQuirk** [comment]
Can't wait to give it a go ! Thanks very much !

Just to be sure, those are the bindings available after having opened **Bukubrow** or can I press `Ctrl+D` anytime and have the popup shown ?

**Comment by SamHH** [comment]
That's only after Bukubrow is open, though you can already open the extension window with Ctrl+Shift+B.
