### ISSUE TITLE
Linux - Firefox - Add bookmark window too small

### ISSUE THREAD

**Issue by BobleChinois** [SamHH/bukubrow#58]
Linux distrib : Linux Mint 18 Sarah
Firefox : 60.0.1 (64 bits)

Reproducible steps : 
1. Open any webpage
2. Click on the bukubrow icon on the top right of the screen
3. Click on the "add a bookmark" icon

Expected behaviour : 
Open a window with empty fields to type tags, comments...

Actual behaviour : 
Open a very small window, almost impractical (see attach files)

![bukubrow-add bookmark_small](https://user-images.githubusercontent.com/11726747/40877359-ee4e3860-667f-11e8-9a33-798b62aca05b.png)

**Comment by wlallemand** [comment]
I have the same problem there, it makes the plugin unusable.

**Comment by SamHH** [comment]
https://github.com/SamHH/bukubrow/commit/023c5ef7617373214784f4e4d3238c74cfcf9cf3

**Comment by SamHH** [comment]
@BobleChinois @wlallemand This is now released on both Firefox and Chrome addon stores as 2.4.0.
