### ISSUE TITLE
wrong path when executing install.sh

### ISSUE THREAD

**Issue by w17t** [SamHH/bukubrow#60]
it seems `browser-hosts/firefox.js` was `firefox-host.json` in the past, which should be corrected in `install.sh`

**Comment by SamHH** [comment]
Nope, you just need to use the [makefile](https://github.com/SamHH/bukubrow/blob/master/makefile#L39); it moves everything where it's expected to be.

I had a similar comment from a Firefox addon reviewer so perhaps I should look at making the documentation clearer.

**Comment by SamHH** [comment]
Relevant: #79
