### ISSUE TITLE
Problem with install.sh file

### ISSUE THREAD

**Issue by bepolymathe** [SamHH/bukubrow#76]
Select your browser:
====================
1) Chrome
2) Chromium
3) Firefox
1-3: 3

Installing Firefox host config
cp: impossible d'évaluer '/home/manu/bukubrow-ci_2018-09-24_b4bd2dc_linux/binary/firefox-host.json': Aucun fichier ou dossier de ce type

**Comment by SamHH** [comment]
The CI releases unfortunately don't really work yet, see #12.

Refer to the [Building the binary](https://github.com/SamHH/bukubrow#building-the-binary) section of the README.

**Comment by bepolymathe** [comment]
It think we need more explications for this point 

> Run make binary-linux-x64 (or substitute binary-linux-x64 for your preferred target) and then inside ./release you'll have a zip identical to what you would have downloaded as a binary in step 1. Note that you'll need your target platform installed and configured with Cargo (Rust package manager).

I have this problem

`  = note: /usr/bin/ld : ne peut trouver -lsqlite3
          collect2: error: ld a retourné le statut de sortie 1
          

error: aborting due to previous error

error: Could not compile `bukubrow`.

To learn more, run the command again with --verbose.
make: *** [makefile:46: binary-linux-x64] Error 101
`

**Comment by bepolymathe** [comment]
Ok, compilation works with libsqlite3x-devel-20071018-24.fc29.x86_64 package install.
Compilation of webext ok too. 
But same error message after installing extension in Firefox
![image](https://user-images.githubusercontent.com/29939805/51740639-dc9c7300-2094-11e9-8251-939ed1a6fb0e.png)

**Comment by SamHH** [comment]
Which exact steps did you follow? I've done the following and all is working on master:

1. `git clone https://github.com/SamHH/bukubrow.git my-dir && cd my-dir`
2. `make binary-linux-x64`
3. `mkdir ~/.bukubrow && mv release/binary-linux-x64.zip ~/.bukubrow && cd ~/.bukubrow` (you can use any directory for this, but it has to stay in the same place after the following steps)
4. `unzip binary-linux-x64.zip`
5. `./install.sh` choose Firefox at the prompt
6. `cd -` (this should take you back to the repo root if you followed these steps exactly)
7. `make webext && cd release && unzip webext.zip`
8. Open Firefox and navigate to `about:debugging#addons`, and select "Load Temporary Add-on...". Navigate to the unzipped WebExtension and select `manifest.json`

I do need to improve the README, but ideally at least I could get CI working and then you could just download stuff pre-packaged as it should be. The awkward way in which binaries interact with the browser doesn't help.

**Comment by bepolymathe** [comment]
Okay great, it works. The compilation is clean this time. 
Indeed it might be nice to add these steps to the readme. 
Thank you for your feedback and for the extension!

**Comment by SamHH** [comment]
No problem, glad to help. Yeah I'm going to create a meta issue for the README and generally how these steps go, it's clearly a mystery for anyone not already intimately familiar with the project! #79
