### ISSUE TITLE
Context menu functionality: bookmark link, bookmark current tab, bookmark all tabs

### ISSUE THREAD

**Issue by paulie-g** [SamHH/bukubrow#93]
Bookmarking multiple tabs, especially all tabs in a window (once you've realized you've gone too far down the rabbit hole) is currently incredibly labour-intensive if done manually, and kludgy if automated by the user. For the read-later use case, it would be a great help if the extension implemented this functionality internally. Since other convenience functionality would be nice to have in a context menu, it would make sense to tack it on. It is my hope that this is something you've thought about already and view as valuable enough to spend time on; normally, I'd say this ought to be a pull request and not an issue, but my js extension clue = 0, so please accept my apologies and thank you for the work you've already done :)

**Comment by SamHH** [comment]
Hmm, so this isn't something that I'd personally find useful, I'm one of those people who curates his open tabs and gasps in horror at everybody else's penchant for leaving dozens or even hundreds open at a time. :laughing: 

That said I can see the appeal for that workflow. How would you envision it being implemented?

Some options off the top of my head:

- Context menu
- Extra button(s) in the main top navigation bar
- New button(s) in the add a bookmark modal

Other notes:
- For something as significant as adding multiple bookmarks automatically without curation, I really think a second step/confirmation dialog is needed. I added a step like this for the "Open All Bookmarks" button as I kept accidentally clicking on it and nearly crashing my browser.
- Are we adding all the tabs from the present/active window, or all tabs from all windows?
- Do we want to be able to select and deselect them in a list with checkboxes?
- Do we want all bookmarks added this way to have be given a particular tag to denote how they were added? If so, is it optional and/or configurable?

**Comment by SamHH** [comment]
Also have you considered the extension Session Boss? That may fit your usecase better.

**Comment by paulie-g** [comment]
Believe it or not, but I have a semi-defensible use case for that. I already use a tab manager for ephemeral things (Chromium/OneTab), the built-in hierarchical tab manager in Qupzilla for tree-structured research related stuff and standard bookmarks for things I have read and want to keep (the latter suboptimal because no multiple tags). I've now added buku for managing a read-later list that does multi-tag. This all works fine. Problem is, for things I intend to read in the next day or so and am not sure I want on my permanent to-read list, I open tabs. Normally this isn't a problem, but at times life intervenes, the time available to read non-essential things evaporates and I need to be able to convert all those open tabs into permanent bookmarks on a secondary to-read list that I can easily search (and export from in future for deep search). Yes, I could kludge something for the ~300+ tabs I need to do that to right now, but I'm unlikely to become more prescient in future.

**Comment by paulie-g** [comment]
I think a context menu wins. That's where virtually all things like tab managers and tab suspenders put such functionality. A context menu implementation would also allow adding the convenient buku this tab/buku this link functions. Other options just add clutter for the sake of functionality some users will never use, at least not often.

1. You're absolutely right, it would need a step before batch addition. It could be a simple confirmation or an interstitial window that allows to add tags to be applied to the whole batch.
2. All tabs from present window. I'm not even sure it's possible to access tabs in other windows under Chrome's security model, but even it it were, it would be too coarse a granularity and no other extension I've seen crosses the window boundary for batch actions on tabs.
3. Additional step to select/deselect with checkboxes may be useful, but it's extra work and is probably best left unimplemented until there is user demand.
4. I wouldn't create a default "added-via-batch" tag, no. I would provide the same interface as currently exists for adding tags in an interstitial window, with the tags to be applied to each bookmark in the batch. Such a dialog would double as confirmation.

**Comment by SamHH** [comment]
There's a challenge with the context menu which I think explains why Session Boss, which I use and mentioned previously, does not provide a context menu option; namely not all browsers support the API to programmatically open the extension popup, including Chrome.

The relevant API is [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup). Whilst this would work in Firefox as the context menu event would quality as a [user action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/User_actions), it's important that this extension maintains full feature-parity between at least Firefox and Chrome, and unfortunately it appears that Chrome's devs are [uninterested in exposing this API publicly](https://bugs.chromium.org/p/chromium/issues/detail?id=399859).

We could inject a modal within the page instead I suppose, but that implies potentially a lot of architectural changes. Perhaps this is viable the more I think about it, though I don't like fragmenting the codebase for all these different entrypoints. Hmm.

**Comment by paulie-g** [comment]
Well, you could always do this:
1. Create a separate "batch add/add from context meny" interface in a tab in the extension pop-up
2. Have the context menu add the urls to a global variable
3. When opening pop-up, check if there's a pending context menu add and select the right tab

**Comment by SamHH** [comment]
Yeah I think that may be the most viable approach. I could practice progressive enhancement and allow Firefox to benefit from the API as well.

- Context menu entry: `Send tabs to Bukubrow` / `Send link to Bukubrow` / etc
- New button in top nav to take you to the new "staging area" (better name TBD) section
- Within said section you can see each group of tabs you've sent to this space
- Clicking on a group of tabs allows you to (de)select any undesired tabs (checkboxes) and add any tags you'd like them all to possess
- Clicking on an individual tab allows you to edit it just as you would a bookmark - I'm preliminarily including this feature because I think it'd be fairly easy to reuse existing components for this.
- Once you've finished editing your group of tabs you can decide what to do with them (naming TBD): Commit to Buku, save back to the list, or cancel and revert changes.

How's this?

**Comment by paulie-g** [comment]
Makes perfect sense, that's likely the optimal design.

**Comment by SamHH** [comment]
The work for this is now pretty much done, it'll be included in the next release. :grin:
