### ISSUE TITLE
GNU/Linux installer bug

### ISSUE THREAD

**Issue by EmilianoCostantini** [SamHH/bukubrow#97]
In version **2.6.0** (downloaded as **tar.gz** file at url https://github.com/samhh/Bukubrow/releases) there seems to be a problem within:
```
    /…/bukubrow-2.6.0/binary/install.sh
```
In step:
```
    # Copy manifest host config file
    cp "$DIR/$BROWSER_HOST_FILENAME" "$TARGET_DIR/$APP_NAME.json"
```

The filepath turns out to be:
```
    /…/bukubrow-2.6.0/binary/firefox-host.json
```
but such a file does not exist, causing the install to fail.

The right filepath should probably be:
```
    /…/bukubrow-2.6.0/binary/browser-hosts/firefox.json
```

**Comment by SamHH** [comment]
Ah, I suspect this is because the README _still_ isn't clear enough :sob: 

Try the zip in release `2.5.0`.

**Comment by EmilianoCostantini** [comment]
This doesn't strike me as a misunderstanding issue.

`"$DIR/$BROWSER_HOST_FILENAME"` resolves itself (in the case of Firefox) in `bukubrow-2.6.0/binary/firefox-host.json`, but such file just isn't there.

It should resolve itself instead in `bukubrow-2.6.0/binary/browser-hosts/firefox.json`, and the same goes for the other browsers.

If it isn't fixed, the GNU/Linux installer just won't work.

**Comment by SamHH** [comment]
Did you try the zip release in `2.5.0`? The source code directory structure won't work unless you run the relevant commands in the makefile, hence the specific releases when the binary is updated.

**Comment by EmilianoCostantini** [comment]
Latest release successfully installed, thank you! :)
I got another problem, but I'll open a new issue for that later on.
